### ISSUE TITLE
bug pach 3.0 mount is lvl 40

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#1]
bug pach 3.0 mount is lvl 40

if you buy a normal mount and do a normal trainer it's ok at vll 30 on pach 3.0 normal at lvl 30 I know it's done

![image](https://github.com/noisiver/mod-progression/assets/79054852/7cec9ec1-4fa6-44fb-bd70-aecc45ec5042)

**Comment by kamila231993** [comment]
paladin problem warlok is lvl 20

**Comment by kamila231993** [comment]
if you buy a normal mount and do a normal trainer it's ok at vll 30 on pach 3.0 normal at lvl 30 I know it's done

**Comment by noisiver** [comment]
Thank you for reporting this, I appreciate it so much. It should hopefully be fixed now!
