### ISSUE TITLE
Emblem of Triumph at Tribunal in Halls of Stone Heroic.  Progression patch configured for 3.0 (editat)

### ISSUE THREAD

**Issue by SpiderNet193** [noisiver/mod-progression#11]
Emblem of Triumph at Tribunal in Halls of Stone Heroic.

Progression patch configured for 3.0 

[<a href="https://freeimage.host/i/JXzvQJ1"><img src="https://iili.io/JXzvQJ1.md.png" alt="JXzvQJ1.md.png" border="0"></a>](url)

**Comment by noisiver** [comment]
Thank you for reporting this. Seems I made a stupid typo when I ported the code over that caused this to happen. It should be fixed now but if you find more occurrences like this please do report them too.
