### ISSUE TITLE
Harold Winston - Epic rings in Dalaran

### ISSUE THREAD

**Issue by SpiderNet193** [noisiver/mod-progression#13]
[<a href="https://freeimage.host/i/JX0Wfx1"><img src="https://iili.io/JX0Wfx1.md.png" alt="JX0Wfx1.md.png" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'>free picture upload</a><br />](url)

Harold Winston in Dalaran sells rings upgrade that were added in later patches. + other EoT and EoC items

**Comment by noisiver** [comment]
Thanks for reporting this, I really do appreciate it.

I will get to work on this NPC right now, go through all items sold to make sure they are changed accordingly. I will hopefully have a fix for this within a short amount of time!

**Comment by noisiver** [comment]
This should hopefully be fixed now but please let me know if I missed anything or if I messed something up along the way!
