### ISSUE TITLE
Patch problem

### ISSUE THREAD

**Issue by Ligth7** [noisiver/mod-progression#15]
I have a problem executing patches, for example: when I try to change it in the config.

Progression.Patch = 17
I implement the sql from that same patch but when entering the kingdom I still see vendors, creatures, missions and others from the 3.3.5 expansion

**Comment by noisiver** [comment]
- Why are you running them manually? The auto updater should take care of it
- You need to run all patches before it

**Comment by Ligth7** [comment]
I don't know if I'm doing it wrong, when configuring previous patches in the config it still comes into play in the current patch 3.3.5.
Import all the sql of each patch manually.
![Screenshot_110](https://github.com/noisiver/mod-progression/assets/102430118/630a2b2d-6087-4fc0-8cd3-b81f47a10a0e)
![Screenshot_111](https://github.com/noisiver/mod-progression/assets/102430118/4950893c-1639-48af-9716-04c4958ebc33)
![Screenshot_112](https://github.com/noisiver/mod-progression/assets/102430118/eb286973-965f-4a83-81bb-cd25952c9f91)

**Comment by noisiver** [comment]
I'm not sure what you're trying to show me. Why is the dungeon finder tool open, what purpose does it serve? If you're trying to say that it shouldn't be, that requires a client patch. You still can't queue without it unless you set Enforce.DungeonFinder to 0.

**Comment by Ligth7** [comment]
Yes, apologies if I don't understand, well what I wanted to do is put the server on Patch 3.0: Echoes of Doom which, by configuring the conf, I would have to change everything to that patch, the dalaran sellers, and the dailies that in this In any case, they would give emblems from that patch as a reward, but it doesn't charge me any of those.
I implemented the sql of that patch manually, but the vendors, missions and others from patch 3.3.5 continue to appear, that was my doubt because the sql in theory would have to change to that patch.
Again, sorry if I don't understand myself.
