### ISSUE TITLE
Reward in Dungeons - Quest_template

### ISSUE THREAD

**Issue by Ligth7** [noisiver/mod-progression#16]
In the 3.0 paths in random it should give (Emblem of valor: 40753) and in the heroic ones after the first dungeon it should give (Emblem of heroism: 40752) in which it is only giving gold as a reward.
*Randoms that are not giving emblems*
17 - Patch 3.0: Echoes of Doom =>Emblema de valor: 40753
18 - Patch 3.1: Secrets of Ulduar => Emblema de conquista: 45624
![Screenshot_130](https://github.com/noisiver/mod-progression/assets/102430118/0155e495-c15c-4d2c-bdcf-9b4e850b5eaa)
![Screenshot_131](https://github.com/noisiver/mod-progression/assets/102430118/524b8dd6-d171-4468-8c36-e91134304ca7)
![Screenshot_132](https://github.com/noisiver/mod-progression/assets/102430118/d005fda8-c765-4875-b3c9-49f6232aca63)

**Comment by noisiver** [comment]
The dungeon finder is by default not available until 3.3. With that in mind I deliberately made it so it doesn't give any emblems until then.

If you want to change it on your end you're more than welcome to so, but I have no intention of doing that.

**Comment by noisiver** [comment]
I finally added this.
