### ISSUE TITLE
First aid problem in 3.0.1 pach

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#2]
You cannot exceed 225 first aid in patch 3.0.1, 

<a href="https://freeimage.host/i/JW90Oqg"><img src="https://iili.io/JW90Oqg.md.png" alt="JW90Oqg.md.png" border="0"></a>

I tested it on 3.3.5a and it seems ok

<a href="https://freeimage.host/i/JW91xQ1"><img src="https://iili.io/JW91xQ1.md.png" alt="JW91xQ1.md.png" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'>upload images for free</a><br />

**Comment by kamila231993** [comment]
3.3.5a is ok problem loked in pach 3.0.1

**Comment by noisiver** [comment]
This is not an issue but working as intended. Prior to patch 3.1 you had to learn Expert First Aid from the book called `Expert First Aid - Under Wraps` and Artisan First Aid from the quest called `Triage`.

**Comment by kamila231993** [comment]
> This is not an issue but working as intended. Prior to patch 3.1 you had to learn Expert First Aid from the book called `Expert First Aid - Under Wraps` and Artisan First Aid from the quest called `Triage`.

![image](https://github.com/noisiver/mod-progression/assets/79054852/8a900853-a336-4963-b283-41ebe07b409a)
