### ISSUE TITLE
Bug first aid loked 225

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#3]
the problem with first aid is that I can't go past lvl 225 on the 3.0.1 patch, 

<a href="https://freeimage.host/i/JWHZArP"><img src="https://iili.io/JWHZArP.md.png" alt="JWHZArP.md.png" border="0"></a>

on 3.3.5a it works perfectly.

<a href="https://freeimage.host/i/JWHZlTJ"><img src="https://iili.io/JWHZlTJ.md.png" alt="JWHZlTJ.md.png" border="0"></a>

**Comment by noisiver** [comment]
I'm looking into the quests

**Comment by kamila231993** [comment]
> I'm looking into the quests

thank you man
