### ISSUE TITLE
Emblem of triumph in pach 3.0

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#4]
[<a href="https://freeimage.host/i/JWcKbCg"><img src="https://iili.io/JWcKbCg.md.png" alt="JWcKbCg.md.png" border="0"></a>](url)

a party of players received emblems of triumph in dungeon hc on patch 3.0

**Comment by kamila231993** [comment]
posible rewards rdf hc?

**Comment by noisiver** [comment]
I have nothing to work with. You say a player got one from a heroic dungeon but never said which one. RDF daily quests should all reward nothing but gold.

**Comment by kamila231993** [comment]
I will look for these problems in more detail and let you know.

**Comment by noisiver** [comment]
The instance of AoWoW I host runs using this module and it doesn't list any dungeon (heroic or normal) that drop Emblem of Triumph except those added in later patches.

The Icecrown Citadel 5-man instances are disabled so it doesn't matter what drops in there. The Argent Tournament instances are also disabled so yet again, it doesn't matter what drops in there.

I have searched through the database and not found anything that drops Emblem of Triumph that is available.

If you could get that extra bit of information I could at least see what's up.

**Comment by noisiver** [comment]
![image](https://github.com/noisiver/mod-progression/assets/5157047/24844582-19ee-472f-92bc-820487017bdd)

This is the reward given by the random heroic dungeon. Random normal is the same but with less gold. That's not how you could get emblems.

**Comment by kamila231993** [comment]
sure

**Comment by kamila231993** [comment]
I'm just waiting when my players do another dungeon, I told them I'll make a screen where those emblems are so we can figure it out

**Comment by kamila231993** [comment]
We identified the problem.

We have progression enabled on path 3.0 and also RDF enabled.
The first RDF Heroic per day gives currently Emblem of Triumph, it should be Emblem of Valor as per the progression patch.

**Comment by noisiver** [comment]
Except that it doesn't.

![image](https://github.com/noisiver/mod-progression/assets/5157047/cf174443-e9f4-487e-8a59-332ffa2cdbab)

It also shouldn't give anything and that was my intention. RDF was added in 3.3 so until then it won't reward you anything aside from gold and I do not plan to change that.

**Comment by kamila231993** [comment]
where can i find this in what file?

**Comment by noisiver** [comment]
Run this on the world database and tell me what it says:
```sql
SELECT ID, RewardItem1, RewardAmount1 FROM quest_template WHERE id IN (24788, 24789);
```

**Comment by kamila231993** [comment]
[<a href="https://freeimage.host/i/JWlfL2j"><img src="https://iili.io/JWlfL2j.md.png" alt="JWlfL2j.md.png" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'>image sharing sites</a><br />](url)

**Comment by noisiver** [comment]
Those are the quests for heroic dungeon (first of the day and continued) and if they are set to not give any rewards (emblems) then how could they? It makes no sense.

**Comment by noisiver** [comment]
If you open the LFG tool and check the heroic info, does it show Emblem of Triumph? Obviously you have to check with a character that hasn't done one for the day. Does it look like this?

![image](https://github.com/noisiver/mod-progression/assets/5157047/f6e932f5-ecea-4e2d-bf80-dd669d9ebaac)

**Comment by kamila231993** [comment]
yep have me implemented shard for transmog

**Comment by noisiver** [comment]
Actually, even if it was broken, it would give Emblem of Frost for the first one of the day so that couldn't be true either.

If you could, check on a character that hasn't done any random heroic for the day and one that has. I don't see how this could be wrong, but I don't use RDF because I'm trying to keep as true to the patch as possible.

**Comment by noisiver** [comment]
> yep have me implemented shard for transmog Bleakmane shard
> 
> [![JWlBPJj.md.png](https://camo.githubusercontent.com/7020169b4635551e977f4857709ed4abcb345f05d820c86281aca7988d9c5d58/68747470733a2f2f69696c692e696f2f4a576c42504a6a2e6d642e706e67)](https://freeimage.host/i/JWlBPJj)

What am I even looking at? You're changing stuff on your end, I can't say how it could or would affect what I've done and can't provide you with a solution if it's not an issue with my module (and I doubt it is)

**Comment by kamila231993** [comment]
I will follow when I do another dungeon guys

**Comment by noisiver** [comment]
Setting Reset to 1 will import all progression files every time you start the server. I always have this set 1 to make sure I don't have issues when updating SQL files, and if I want to go backwards in patches (for example 3.3 to 3.1 etc)

**Comment by kamila231993** [comment]
aaaaaaaaa lol

Old kingdom
Draktharon dungeons
Drop triumph
And daily quest have bug
The Culling of Stratholme daily quest


here problem triumph

**Comment by kamila231993** [comment]
I don't know for sure, check with yourself, please, to be sure, maybe the problem was only with me from the progression

**Comment by kamila231993** [comment]
[<a href="https://freeimage.host/i/JW0iAas"><img src="https://iili.io/JW0iAas.md.png" alt="JW0iAas.md.png" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'>free picture hosting</a><br />](url)

**Comment by kamila231993** [comment]
you can close this post, it is fixed, if there are any more problems, I will reopen it
