### ISSUE TITLE
Frozo shouldnt be here. He was added 3.3.5 with RS release, you can literally buy T8 and T9 Mats from him right now 

### ISSUE THREAD

**Issue by kamila231993** [noisiver/mod-progression#7]
Frozo shouldnt be here. He was added 3.3.5 with RS release, you can literally buy T8 and T9 Mats from him right now (editat)

<a href="https://freeimage.host/i/JWXkXUu"><img src="https://iili.io/JWXkXUu.md.png" alt="JWXkXUu.md.png" border="0"></a><br /><a target='_blank' href='https://freeimage.host/'>online photo hosting</a><br />

**Comment by noisiver** [comment]
Fixed.
